[package]
name = "ping-pong"
version = "0.0.2"
authors = ["Bruda Claudiu-Marcel <claudiu725@yahoo.com>"]
edition = "2018"
publish = false

[lib]
path = "src/ping_pong.rs"
[dependencies.dharitri-sc]
version = "0.12.4"
[dev-dependencies.dharitri-sc-scenario]
version = "0.12.4"
