[package]
name = "ping-pong-meta"
version = "0.0.0"
authors = ["Bruda Claudiu-Marcel <claudiu725@yahoo.com>"]
edition = "2018"
publish = false
[dependencies.ping-pong]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.12.4"
